config/routes.rb
Rails.application.routes.draw do
  resources :users, only: %i[show edit update index]
  resources :messages, only: %i[index new create]
  resources :rooms, only: %i[index show]
  resources :chats, only: [:create]
  resources :user_rooms, only: [:create]
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  root 'homes#top'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
    belongs_to :room
    belongs_to :user
    validates :chat_message, length: { maximum: 60 }
    
end

app/models/message.rb
class Message < ApplicationRecord
  validates :message, presence: true,
                      length: { maximum: 200 }
  belongs_to :user
end

app/models/room.rb
class Room < ApplicationRecord
    has_many :chats
    has_many :user_rooms
    has_many :users, through: :user_rooms
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token
  before_save { email.downcase! }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d-]+)*\.[a-z]+\z/i
  validates :email, presence: true,
                  format: { with: VALID_EMAIL_REGEX },
                  uniqueness: {case_sensitive: false}
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  validates :name, presence: true
  validates :introduction, length: { maximum: 200 }
  has_many :user_rooms, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :chats, dependent: :destroy
  has_many :rooms, through: :user_rooms

  attachment :user_image

  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def self.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
    include SessionsHelper
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  
  def create
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @messages = Message.all
  end

  def new
    @message = Message.new
  end
  
  def create
    @message = Message.new(message_params)
    # debugger
    @message.user_id = current_user.id
    @message.save
    flash[:success] = "投稿しました！"
    redirect_to '/messages'
  end
  
  private
    def message_params
      params.require(:message).permit(:message)
    end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @rooms = current_user.rooms
    @users = []
    @rooms.each do |room|
      if room.users.first == current_user
        @users << room.users.second
      else
        @users << room.users.first
      end
  end
  
  def show
    room = Room.find(params[:id])
    if room.users.first == current_user
      @user = room.users.second
    else
      @user = room.users.first
    end
    my_room_ids = current_user.user_rooms.pluck(:room_id)
    unless chat_room = UserRoom.find_by(user_id: @user.id, room_id: my_room_ids)
      @room = Room.create
      UserRoom.create(user_id: current_user.id, room_id: @room.id)
      UserRoom.create(user_id: @user.id, room_id: @room.id)
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    
    def new
    end
    
    def create
    user = User.find_by(email: params[:session][:email].downcase)
      if user && user.authenticate(params[:session][:password])
        log_in user
        params[:session][:remember_me] == "1" ? remember(user) : forget(user)
        flash[:success] = "ログインしました"
        redirect_to user
      else
        
        render 'new'
      end
    end
    
    def destroy
      log_out if logged_in?
      flash[:success] = "ログアウトしました！"
      redirect_to root_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @messages = Message.where(user_id: params[:id])
  end

  def edit
    @user = current_user
  end
  
  def index
    @users  = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "登録が完了しました！"
      redirect_to @user
    else
      flash.now[:danger] = "登録に失敗しました・・・"
      render 'new'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name,
                                   :email,
                                   :user_image,
                                   :introduction,
                                   :password,
                                   :password_confirmation
                                   )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    
  def log_in(user)
  	session[:user_id] = user.id
  end
  
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end
  
  def current_user
  	if (user_id = session[:user_id])
  	  @current_user ||= User.find_by(id: user_id)
  	elsif (user_id = cookies.signed[:user_id])
  	  user = User.find_by(id: user_id)
  	  if user && user.authenticated?(cookies[:remember_token])
  	    log_in user
  	    @current_user = user
  	  end
  	end
  end
  
  def logged_in?
    !current_user.nil?
  end
  
  def forget(user)
    user.forget
    cookies.delete(:remember_token)
    cookies.delete(:user_id)
  end
  
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-inverse">
  <div class="container-fluid">
    <%= link_to "Mini_chat", root_path, id: "logo" %>
    <nav>
      <ul class="navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <% if logged_in? %>
          <li><%= link_to "タイムライン", messages_path %></li>
          <li><%= link_to "チャットルーム", rooms_path %></li>
          <li><%= link_to "マイページ", current_user %></li>
          <li><%= link_to "Log out", logout_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MiniChat</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header'%>
    <div class="container">
      <% flash.each do |message_type, message| %>
          <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/index.html.erb
<h1 class="text-center">投稿一覧</h1>
<% @messages.each do |message| %>
<div class="message-box">
  <p class="p-3"><%= message.user.name %></p>
  <p class="text-center">
    <%= message.message %>
  </p>
</div>
<% end %>

app/views/messages/new.html.erb
<div class="messages-form col-md-8 mx-auto">
  <h1 class="text-center">何か投稿しましょう！</h1>
  <%#= render 'shared/error_messages', @user: @message %>
  <%= form_with model: @message, local: true do |f| %>
    <div class="form-group">
      <div>
        <%= f.label :message, "200文字以内です" %>
        <%= f.text_area :message, class: "form-control" %>
        
        <%= f.submit "投稿する", class: "btn btn-prymary" %>
        <% end %>
    </div>
  </div>
</div>

app/views/rooms/index.html.erb
<h1>チャットルーム一覧</h1>
<% @users.each do |user| %>
<p><%= user.name %>さんとのチャット</p>
<% end >

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1><%= @user.name %>さんの編集ページ</h1>
<div class="form-group">
  <%= form_with model: current_user, local: true do |f| %>
  
    <%= f.label :name, "名前" %>
    <%= f.text_field :name, class: "form-control" %>
    
    <%= f.label :email, "メールアドレス" %>
    <%= f.email_field :email, class: "form-control" %>
    
    <%= f.label :introduction, "紹介文" %>
    <%= f.text_area :introduction, class: "form-controll" %>
    
    <%= f.label :user_image, "プロフィール画像" %>
    <%= f.attachment_field :user_image %>
    
    <%= f.submit "編集する", class: "btn btn-warning" %>
  <% end %>
</div>

app/views/users/new.html.erb
<h1 class="text-center">Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: signup_path) do |f| %>
    <%= render 'shared/error_messages' %>
      <%= f.label :name, "名前" %>
      <%= f.text_field :name, class: "form-control" %>
      
      <%= f.label :email, "メールアドレス" %>
      <%= f.email_field :email, class: "form-control" %>
      
      <%= f.label :password, "パスワード（６文字以上）" %>
      <%= f.password_field :password, class: "form-control" %>
      
      <%= f.label :password_confirmation, "確認用パスワード" %>
      <%= f.password_field :password_confirmation, class: "form-control" %>
      
      <%= f.submit "アカウントを作成する", class: "btn btn-danger" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div>
  <section class="user_info">
    <h1 class="text-center">
      <%= @user.name %>さんのマイページ
    </h1>
    <%= link_to "投稿する", new_message_path, class: "btn btn-primary" %>
    <% if @user == current_user %>
      <%= link_to "編集する", edit_user_path, class: "btn btn-warning" %>
    <% else %>
      <% link_to "チャットする", room_path, class: "btn btn-warning" %>
    <% end %>
  </section>
</div>
<div>
  <% @messages.each do |message| %>
  <div class="message-box">
    <p class="text-center"><%= message.message %></p>
  </div>
  <% end %>
</div>